---
title: "Jake Rozran's resume"
author: Jake Rozran
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
      css:
          - override.css
          - resume
      self_contained: true
# uncomment this line to produce HTML and PDF in RStudio:
#knit: pagedown::chrome_print
---

Aside
================================================================================

Contact Info {#contact}
--------------------------------------------------------------------------------

- <i class="fa fa-envelope"></i> jacob.rozran@gmail.com
- <i class="fa fa-github"></i> [github.com/jrozra200](https://github.com/jrozra200)
- <i class="fa fa-phone"></i> (410) 231-9371
- Address
- LinkedIn
- Twitter


Skills {#skills}
--------------------------------------------------------------------------------

- Fraud Detection
- Risk Modeling
- R/RStudio
- Data Visualization
- Python/Jupyter
- Databases/SQL
- Statistics/Modeling
- Bash & Git


Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

Last updated on `r format(Sys.Date(), "%B %d, %Y")`.



Main
================================================================================

Jake Rozran {#title}
--------------------------------------------------------------------------------

### About Me

In addition to being a leader, dad, uncle, & data guy, I am a data & technology 
professional with real-world experience in data science, data analytics, data 
engineering, fraud detection, risk modeling, building and maintaining data teams, 
project management, sales, consulting, and teaching. 

My passion for data and statistics has inspired me to become an Adjunct 
Professor of Statistics, which has improved my ability to explain complex 
subjects to all levels of understanding. I love to learn in general and am a 
data fanatic.

On a more personal note, I love being a husband, father, and uncle. I also love 
being active - soccer, running, cycling, hiking, lifting - and taking pictures 
(usually of my kids).


Professional Experience {data-icon=suitcase}
--------------------------------------------------------------------------------

### Data Scientist Practice Lead

CivicActions

San Francisco, CA

2021

- Building a Data Science Practice Area with > $1MM revenue after 6 months; focused on data solutions, people management, sales, marketing, and project management.
- For the Centers of Medicare and Medicaid (CMS), leveraging Natural Language Processing (NLP) in the creation and evaluation of System Security Plans (SSPs) to optimize the Authority to Operate (ATO) process.
- For the Centers of Medicare and Medicaid (CMS), analyzing AWS usage to forecast annual usage and identify efficiencies. 

### Adjunct Professor

Villanova University

Villanova, PA

2020-2021

- Build the syllabus, lectures, assignments, and tests for undergraduate Intro to Statistics and Intro to Statistics for Biology courses.
- Advise and mentor students by writing recommendations for various programs, helping guide studies for real-world success after graduation, and providing helping hand and ear through the stresses of university life. 

### Solutions Consultant

Socure

New York, NY

2020-2021

- Technical expert on fraud prevention, Know Your Customer (KYC)/Customer Identification Program (CIP), Socure product modules, data science, statistics, and data viz in support of the sales and onboarding processes.




Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

### Beijing University of Chemical Technology

B.S. in Information and Computing Sciences

Beijing, China

2010

Thesis: Dyadic wavelet and its application in edge detection

### University of Chinese Academy of Sciences

M.S. in Bioinformatics

Beijing, China

2014

Thesis: A multi-omics study for intra-individual divergence of the distributions between mRNA isoforms in mammals

