---
name: Jake Rozran
position: "Data Professional\n\nAdjunct Professor"
address: "1400 Maryland Ave.\n\nHavertown, PA 19083"
phone: (410) 231-9371
profilepic: mariecurie.jpg
www: jakelearnsdatascience.com
email: "jacob.rozran@gmail.com"
twitter: StatsManPHL
github: jrozra200
linkedin: jacob-rozran
date: "`r format(Sys.time(), '%B %Y')`"
aboutme: "Jake is a leader, fixer, builder, helper, learner, dad, uncle, & data guy. I am a data professional who has real-world experience putting data products into production and building data teams. I am curious, constantly learning, and improving - staying up to date with trends in all facets of the data science life cycle.\n\nAdditionally, I am an Adjunct Professor of Statistics who excels at teaching complex topics at all levels of understanding. I love to learn in general, but mostly I am a data fanatic."
output: vitae::twentyseconds
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
```

\begin{center}

```{r, out.width = "65%"}
library(VennDiagram)
venn.plot <- draw.triple.venn(
        area1 = 65,
        area2 = 75,
        area3 = 85,
        n12 = 35,
        n23 = 15,
        n13 = 25,
        n123 = 5,
        category = c("Coding/\nData", "Statistics", "Leadership"),
        fill = c("#1d6ae5", "#5DADE2", "#19396b"),
        cat.cex = 1.5,
        cat.col = c("#1d6ae5", "#5DADE2", "#19396b"),
        cex = c(0, 0, 0, 0, 0, 0, 0)
)
```

\end{center}

# Data Science Skills

\btwocol
* R/RStudio - Expert
* Data Visualization - Expert
* MS Excel - Expert
* Python/Jupyter - Advanced
* Statistics/Modeling - Advanced
* Databases - Intermediate
* Bash - Intermediate
* SAS - Novice

\etwocol

# Experience

```{r}
library(tibble)
tribble(
        ~ role, ~ company, ~ loc, ~ dates,
        "Solutions Consultant", "Socure", "New York, NY", "2020-Pres.",
        "Adjunct Professor of Statistics", "Villanova University", "Villanova, PA", "2020-Pres.",
        "Manager of Data Analytics", "Comcast: Xfinity Mobile Risk Mgmt", "Philadelphia, PA", "2017-2020",
        "Senior Data Analyst", "Comcast: Internet Services Eng", "Philadelphia, PA", "2014-2017",
        "Project Manager", "Comcast: Messaging Application Eng", "Philadelphia, PA", "2013-2014",
        "Implementation Manager", "Booz Allen Hamilton", "Rockville, MD", "2010-2013",
        "Financial Analyst/Project Manager", "Booz Allen Hamilton", "Lexington Park, MD", "2009-2010",
        ) %>% detailed_entries(role, dates, company, loc)
```

# Volunteer

```{r}
tribble(
        ~ role, ~ company, ~ loc, ~ dates,
        "Organizer", "Data Jawn Conference", "Philadelphia, PA", "2019-Pres.",
        "Data Analyst", "Montgomery County Public Defender", "Norristown, PA", "2016-2017"
        ) %>% detailed_entries(role, dates, company, loc)
```

# Education

```{r}
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where,
  "Masters of Science - Applied Statistics", "2015-2017", "Villanova University", "Villanova, PA",
  "Bachelors of Science - Business & Engineering", "2004-2009", "Drexel University", "Philadelphia, PA"
) %>% 
  detailed_entries(Degree, Year, Institution, Where)
```

